version: '3'

services:
  base:
    build:
      context: ./base
      dockerfile: Dockerfile
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - base
    volumes:
      - ./datas:/var/app/datas
    ports:
      - 4000:4000
    entrypoint: ./server
    working_dir: /var/app

